import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../global.css";
import Image from "next/image";
import AuthButtonServer from "../components/authButtonServer";
import { AuthAdminApi } from "@supabase/supabase-js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <body className="bg-green-100">
        <header className="bg-green-200 text-gray-600 body-font ">
          <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a href="/userpage/home">
              <Image
                src="/logo.jpg"
                alt="デートプランのロゴです"
                width={30}
                height={30}
                className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
              />
            </a>
            <nav className="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400	flex flex-wrap items-center text-base justify-center">
              <a className="mr-5 hover:text-gray-900" href="/userpage/home">
                HOME
              </a>
              <a className="mr-5 hover:text-gray-900" href="/userpage/calendar">
                SCHEDULE
              </a>
              <a className="mr-5 hover:text-gray-900" href="/userpage/lover">
                LOVER
              </a>
              <a
                className="mr-5 hover:text-gray-900"
                href="/userpage/makeplans"
              >
                PLAN
              </a>
            </nav>
            <AuthButtonServer />
          </div>
        </header>
        {children}
      </body>
    </>
  );
}

//      <body className={inter.className}>
